services:
  orchestrator:
    build: orchestrator
    container_name: orchestrator
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017/orchestrator
      - FX_QUOTE_SERVICE_URL=http://fx-quote-service:8001
      - PAYOUT_PARTNER_SIMULATOR_SERVICE_URL=http://payout-partner-simulator:8002
      - PORT=8000
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    depends_on:
      - mongo
      - fx-quote-service
      - payout-partner-simulator

  fx-quote-service:
    build: fx-quote-service
    container_name: fx-quote-service
    ports:
      - "8001:8001"
    expose:
      - "8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
      - DB_URI=mongodb://mongo:27017/fx-quote-service
    depends_on:
      - mongo

  payout-partner-simulator:
    build: payout-partner-simulator
    container_name: payout-partner-simulator
    ports:
      - "8002:8002"
    expose:
      - "8002"
    environment:
      - PORT=8002
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017/payout-partner-simulator
      - ORCHESTRATOR_SERVICE_URL=http://orchestrator:8000
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    depends_on:
      - mongo

  test-runner:
    build: .
    container_name: test-runner
    environment:
      - NODE_ENV=development
      - ORCHESTRATOR_SERVICE_URL=http://orchestrator:8000
      - FX_QUOTE_SERVICE_URL=http://fx-quote-service:8001
      - PAYOUT_PARTNER_SIMULATOR_SERVICE_URL=http://payout-partner-simulator:8002
    depends_on:
      - mongo
      - orchestrator
      - fx-quote-service
      - payout-partner-simulator

  mongo:
    image: mongo:8
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet"]
volumes:
  mongo_data: