export enum ComplianceDecisions {
  APPROVED_AUTOMATICALLY = "APPROVED_AUTOMATICALLY",
  REJECTED_AUTOMATICALLY = "REJECTED_AUTOMATICALLY",
  APPROVED_MANUALLY = "APPROVED_MANUALLY",
  REJECTED_MANUALLY = "REJECTED_MANUALLY",
  PENDING = "PENDING",
}

export const complianceDecisionValues = Object.values(ComplianceDecisions);