export enum ReconciliationStatus {
  MATCHED_EXACT = "MATCHED_EXACT",
  MATCHED_WITH_TOLERANCE = "MATCHED_WITH_TOLERANCE",
  STATUS_MISMATCH = "STATUS_MISMATCH",
  AMOUNT_MISMATCH = "AMOUNT_MISMATCH",
  CURRENCY_MISMATCH = "CURRENCY_MISMATCH",
  MISSING_PAYOUT = "MISSING_PAYOUT",
  MISSING_TRANSFER = "MISSING_TRANSFER",
  UNKNOWN_MISMATCH = "UNKNOWN_MISMATCH",
  UNDER_INVESTIGATION = "UNDER_INVESTIGATION",
  RESOLVED = "RESOLVED",
}

export const ReconciliationStatusValues = Object.values(
  ReconciliationStatus,
) as string[];
