export enum TaskHandlers {
  QUOTE_TRANSFER = "QUOTE_TRANSFER",
  CHECK_COMPLIANCE = "CHECK_COMPLIANCE",
  INITIATE_PAYOUT = "INITIATE_PAYOUT",
  CANCEL_TRANSFER = "CANCEL_TRANSFER",
  REJECT_TRANSFER = "REJECT_TRANSFER",
}

export const TaskHandlerValues = Object.values(TaskHandlers);